# usage: nmake -f Makefile.nmake

LD = link
EXE = bin\nsocks.exe bin\ssocksd.exe bin\ssocks.exe bin\rssocks.exe bin\rcsocks.exe

!IF [@copy /y config.h.win32 src\config.h]
!ENDIF

all: $(EXE)

{src}.c{bin}.obj:
  @if not exist bin mkdir bin
  $(CC) /c /Isrc /Fobin\ $<

$(EXE): bin\*.obj
  $(LD) /out:$@ ws2_32.lib $<
